version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: docx2pdf-api
    environment:
      - ENV=production
      - STORAGE_ROOT=/data
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=docx2pdf
      - POSTGRES_USER=docx2pdf
      - POSTGRES_PASSWORD=docx2pdf
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SOFFICE_BIN=soffice
    volumes:
      - shared_data:/data
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: docx2pdf-worker
    environment:
      - ENV=production
      - STORAGE_ROOT=/data
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=docx2pdf
      - POSTGRES_USER=docx2pdf
      - POSTGRES_PASSWORD=docx2pdf
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - SOFFICE_BIN=soffice
    volumes:
      - shared_data:/data
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=docx2pdf
      - POSTGRES_USER=docx2pdf
      - POSTGRES_PASSWORD=docx2pdf
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  shared_data:
  pgdata:
